[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
actix-files = "0.6.0"
mongodb = "2.1.0"
futures = "0.3.21"
env_logger = "0.9.0"

[dependencies.portfolio]
path = ".."